name: Flutter release
on:
  # Triggered when a new release is tagged in GitHub.
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# token from https://dart.dev/tools/pub/automated-publishing
jobs:
  publishing:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      #- uses: subosito/flutter-action@v2
      #  with:
      #    flutter-version: '3.0.5'
      #- name: Install dependencies
      #  run: flutter pub get
      # Here you can insert custom steps you need
      # - run: dart tool/generate-code.dart
      - name: Publish
        run: dart pub publish --force
