name: Flutter release
on:
  # Triggered when a new release is tagged in GitHub.
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        
      - name: '>> Dart package <<'
        #uses: k-paxian/dart-package-publisher@master
        uses: sakebook/actions-flutter-pub-publisher@v1.4.0
        with:
          credential: ${{ secrets.FLUTTER_CREDENTIAL_JSON }}
          flutter_package: false
          #credentialJson: ${{ secrets.FLUTTER_CREDENTIAL_JSON }}
